# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: statswr

service: statswr-backend-api
functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 5555
    noPrependStageInUrl: true