export const navItems = [
    { label: "Home", to: "/" },
    { label: "Tier List", to: "/tierlist" }
];

export const regionRankPatch = [
    { label: "\"Global\"", imgSrc: "assets/misc/global-icon.svg" },
    { label: "Diamond+", imgSrc: "assets/misc/diamond-icon.png" },
    { label: "Version: 6.0B", imgSrc: "/" }
];

export const allChampions = [
    { label: "AATROX", name: "Aatrox", role: [0, 1, 2], title: "THE DARKIN BLADE" },
    { label: "AHRI", name: "Ahri", role: [0, 3], title: "THE NINE-TAILED FOX" },
    { label: "AKALI", name: "Akali", role: [0, 1, 3], title: "THE ROGUE ASSASSIN" },
    { label: "AKSHAN", name: "Akshan", role: [0, 1, 3], title: "THE ROGUE SENTINEL" },
    { label: "ALISTAR", name: "Alistar", role: [0, 5], title: "THE MINOTAUR" },
    { label: "AMBESSA", name: "Ambessa", role: [0, 1], title: "MATRIARCH OF WAR" },
    { label: "AMUMU", name: "Amumu", role: [0, 1, 2], title: "THE SAD MUMMY" },
    { label: "ANNIE", name: "Annie", role: [0, 3], title: "THE DARK CHILD" },
    { label: "ASHE", name: "Ashe", role: [0, 4, 5], title: "THE FROST ARCHER" },
    { label: "AURELION_SOL", name: "Aurelion Sol", role: [0, 3], title: "THE STAR FORGER" },
    { label: "BLITZCRANK", name: "Blitzcrank", role: [0, 5], title: "THE GREAT STEAM GOLEM" },
    { label: "BRAND", name: "Brand", role: [0, 3, 5], title: "THE BURNING VENGEANCE" },
    { label: "BRAUM", name: "Braum", role: [0, 5], title: "THE HEART OF THE FRELJORD" },
    { label: "CAITLYN", name: "Caitlyn", role: [0, 1, 4], title: "THE SHERIFF OF PILTOVER" },
    { label: "CAMILLE", name: "Camille", role: [0, 1], title: "THE STEEL SHADOW" },
    { label: "CORKI", name: "Corki", role: [0, 3, 4], title: "THE DARING BOMBARDIER" },
    { label: "DARIUS", name: "Darius", role: [0, 1, 2], title: "THE HAND OF NOXUS" },
    { label: "DIANA", name: "Diana", role: [0, 2, 3], title: "SCORN OF THE MOON" },
    { label: "DRAVEN", name: "Draven", role: [0, 4], title: "THE GLORIOUS EXECUTIONER" },
    { label: "EKKO", name: "Ekko", role: [0, 2, 3], title: "THE BOY WHO SHATTERED TIME" },
    { label: "EVELYNN", name: "Evelynn", role: [0, 2], title: "AGONY'S EMBRACE" },
    { label: "EZREAL", name: "Ezreal", role: [0, 3, 4], title: "THE PRODIGAL EXPLORER" },
    { label: "FIDDLESTICKS", name: "Fiddlesticks", role: [0, 2], title: "THE ANCIENT FEAR" },
    { label: "FIORA", name: "Fiora", role: [0, 1], title: "THE GRAND DUELIST" },
    { label: "FIZZ", name: "Fizz", role: [0, 2, 3], title: "THE TIDAL TRICKSTER" },
    { label: "GALIO", name: "Galio", role: [0, 3, 5], title: "THE COLOSSUS" },
    { label: "GAREN", name: "Garen", role: [0, 1], title: "THE MIGHT OF DEMACIA" },
    { label: "GRAGAS", name: "Gragas", role: [0, 1, 2, 3], title: "THE RABBLE ROUSER" },
    { label: "GRAVES", name: "Graves", role: [0, 1, 2], title: "THE OUTLAW" },
    { label: "GWEN", name: "Gwen", role: [0, 1, 2], title: "THE HALLOWED SEAMSTRESS" },
    { label: "HECARIM", name: "Hecarim", role: [0, 2], title: "THE SHADOW OF WAR" },
    { label: "HEIMERDINGER", name: "Heimerdinger", role: [0, 3, 5], title: "THE REVERED INVENTOR" },
    { label: "IRELIA", name: "Irelia", role: [0, 1, 3], title: "THE BLADE DANCER" },
    { label: "JANNA", name: "Janna", role: [0, 5], title: "THE STORM'S FURY" },
    { label: "JARVAN_IV", name: "Jarvan IV", role: [0, 2], title: "THE EXAMPLAR OF DEMACIA" },
    { label: "JAX", name: "Jax", role: [0, 1, 2], title: "GRANDMASTER AT ARMS" },
    { label: "JAYCE", name: "Jayce", role: [0, 1, 3], title: "THE DEFENDER OF TOMORROW" },
    { label: "JHIN", name: "Jhin", role: [0, 4], title: "THE VIRTUOSO" },
    { label: "JINX", name: "Jinx", role: [0, 4], title: "THE LOOSE CANNON" },
    { label: "KAISA", name: "Kai\'sa", role: [0, 4], title: "DAUGHTER OF THE VOID" },
    { label: "KALISTA", name: "Kalista", role: [0, 1, 4], title: "THE SPEAR OF VENGEANCE" },
    { label: "KARMA", name: "Karma", role: [0, 3, 5], title: "THE ENLIGHTENED ONE" },
    { label: "KASSADIN", name: "Kassadin", role: [0, 3], title: "THE VOID WALKER" },
    { label: "KATARINA", name: "Katarina", role: [0, 3], title: "THE SINISTER BLADE" },
    { label: "KAYLE", name: "Kayle", role: [0, 1, 3], title: "THE RIGHTEOUS" },
    { label: "KAYN", name: "Kayn", role: [0, 2], title: "THE SHADOW REAPER" },
    { label: "KENNEN", name: "Kennen", role: [0, 1, 3], title: "THE HEART OF THE TEMPEST" },
    { label: "KHAZIX", name: "Kha\'zix", role: [0, 2], title: "THE VOIDREAVER" },
    { label: "KINDRED", name: "Kindred", role: [0, 2], title: "THE ETERNAL HUNTERS" },
    { label: "LEE_SIN", name: "Lee Sin", role: [0, 2], title: "THE BLIND MONK" },
    { label: "LEONA", name: "Leona", role: [0, 5], title: "THE RADIANT DAWN" },
    { label: "LILLIA", name: "Lillia", role: [0, 2], title: "THE BASHFUL BLOOM" },
    { label: "LISSANDRA", name: "Lissandra", role: [0, 1, 3, 5], title: "THE ICE WITCH" },
    { label: "LUCIAN", name: "Lucian", role: [0, 1, 3, 4], title: "THE PURIFIER" },
    { label: "LULU", name: "Lulu", role: [0, 5], title: "THE FAE SORCERESS" },
    { label: "LUX", name: "Lux", role: [0, 3, 5], title: "THE LADY OF LUMINOSITY" },
    { label: "MALPHITE", name: "Malphite", role: [0, 1, 3, 5], title: "SHARD OF THE MONOLITH" },
    { label: "MASTER_YI", name: "Master Yi", role: [0, 2], title: "THE WUJU BLADESMAN" },
    { label: "MILIO", name: "Milio", role: [5], title: "THE GENTLE FLAME" },
    { label: "MISS_FORTUNE", name: "Miss Fortune", role: [0, 3, 4, 5], title: "THE BOUNTY HUNTER" },
    { label: "MORDEKAISER", name: "Mordekaiser", role: [0, 1, 2], title: "THE IRON REVENANT" },
    { label: "MORGANA", name: "Morgana", role: [0, 2, 3, 5], title: "THE FALLEN" },
    { label: "DR_MUNDO", name: "Dr. Mundo", role: [0, 1, 2], title: "THE MADMAN OF ZAUN" },
    { label: "NAMI", name: "Nami", role: [0, 5], title: "THE TIDECALLER" },
    { label: "MAOKAI", name: "Maokai", role: [0, 1, 2, 5], title: "THE TWISTED TREANT" },
    { label: "NASUS", name: "Nasus", role: [0, 1], title: "THE CURATOR OF THE SANDS" },
    { label: "NAUTILUS", name: "Nautilus", role: [0, 1, 2, 5], title: "THE TITAN OF THE DEPTHS" },
    { label: "NILAH", name: "Nilah", role: [0, 4], title: "THE JOY UNBOUND" },
    { label: "NUNU_WILLUMP", name: "Nunu & Willump", role: [0, 2], title: "THE BOY AND HIS YETI" },
    { label: "OLAF", name: "Olaf", role: [0, 1, 2], title: "THE BERSERKER" },
    { label: "ORIANNA", name: "Orianna", role: [0, 3], title: "THE LADY OF CLOCKWORK" },
    { label: "ORNN", name: "Ornn", role: [0, 1], title: "THE FIRE BELOW THE MOUNTAIN" },
    { label: "PANTHEON", name: "Pantheon", role: [0, 1, 2, 3, 5], title: "THE UNBREAKABLE SPEAR" },
    { label: "PYKE", name: "Pyke", role: [0, 5], title: "THE BLOODHARBOR RIPPER" },
    { label: "RAKAN", name: "Rakan", role: [0, 5], title: "THE CHARMER" },
    { label: "RAMMUS", name: "Rammus", role: [0, 2], title: "THE ARMORDILLO" },
    { label: "RENEKTON", name: "Renekton", role: [0, 1], title: "THE BUTCHER OF THE SANDS" },
    { label: "RENGAR", name: "Rengar", role: [0, 1, 2], title: "THE PRIDESTALKER" },
    { label: "RIVEN", name: "Riven", role: [0, 1, 2], title: "THE EXILE" },
    { label: "RUMBLE", name: "Rumble", role: [0, 1, 2, 3, 5], title: "THE MECHANIZED MENACE" },
    { label: "SAMIRA", name: "Samira", role: [0, 4], title: "THE DESERT ROSE" },
    { label: "SENNA", name: "Senna", role: [0, 5], title: "THE REDEEMER" },
    { label: "SERAPHINE", name: "Seraphine", role: [0, 3, 4, 5], title: "THE STARRY-EYED SONGSTRESS" },
    { label: "SETT", name: "Sett", role: [0, 1, 5], title: "THE BOSS" },
    { label: "SHEN", name: "Shen", role: [0, 1], title: "THE EYE OF TWILIGHT" },
    { label: "SHYVANA", name: "Shyvana", role: [0, 2], title: "THE HALF-DRAGON" },
    { label: "SINGED", name: "Singed", role: [0, 1], title: "THE MAD CHEMIST" },
    { label: "SION", name: "Sion", role: [0, 1], title: "THE UNDEAD JUGGERNAUT" },
    { label: "SIVIR", name: "Sivir", role: [0, 4], title: "THE BATTLE MISTRESS" },
    { label: "SONA", name: "Sona", role: [0, 5], title: "MAVEN OF THE STRINGS" },
    { label: "SORAKA", name: "Soraka", role: [0, 5], title: "THE STARCHILD" },
    { label: "SWAIN", name: "Swain", role: [0, 3, 5], title: "THE NOXIAN GRAND GENERAL" },
    { label: "SYNDRA", name: "Syndra", role: [0, 3], title: "THE DARK SOVEREIGN" },
    { label: "TALON", name: "Talon", role: [0, 2, 3], title: "THE BLADE'S SHADOW" },
    { label: "TEEMO", name: "Teemo", role: [0, 1, 3], title: "THE SWIFT SCOUT" },
    { label: "THRESH", name: "Thresh", role: [0, 5], title: "THE CHAIN WARDEN" },
    { label: "TRISTANA", name: "Tristana", role: [0, 1, 3, 4], title: "THE YORDLE GUNNER" },
    { label: "TRYNDAMERE", name: "Tryndamere", role: [0, 1, 2], title: "THE BARBARIAN KING" },
    { label: "TWISTED_FATE", name: "Twisted Fate", role: [0, 1, 3], title: "THE CARD MASTER" },
    { label: "TWITCH", name: "Twitch", role: [0, 2, 4], title: "THE PLAGUE RAT" },
    { label: "URGOT", name: "Urgot", role: [0, 1], title: "THE DREADNOUGHT" },
    { label: "VARUS", name: "Varus", role: [0, 1, 4], title: "THE ARROW OF RETRIBUTION" },
    { label: "VAYNE", name: "Vayne", role: [0, 1, 4], title: "THE NIGHT HUNTER" },
    { label: "VEIGAR", name: "Veigar", role: [0, 3, 5], title: "THE TINY MASTER OF EVIL" },
    { label: "VEX", name: "Vex", role: [0, 3], title: "THE GLOOMIST" },
    { label: "VI", name: "Vi", role: [0, 2], title: "THE PILTOVER ENFORCER" },
    { label: "VIKTOR", name: "Viktor", role: [0, 1, 3], title: "THE HERALD OF THE ARCANE" },
    { label: "VIEGO", name: "Viego", role: [0, 1, 2], title: "THE RUINED KING" },
    { label: "VLADIMIR", name: "Vladimir", role: [0, 1, 3], title: "THE CRIMSON REAPER" },
    { label: "VOLIBEAR", name: "Volibear", role: [0, 1, 2], title: "THE RELENTLESS STORM" },
    { label: "WARWICK", name: "Warwick", role: [0, 1, 2], title: "THE UNCAGED WRATH OF ZAUN" },
    { label: "WUKONG", name: "Wukong", role: [0, 1, 2], title: "THE MONKEY KING" },
    { label: "XAYAH", name: "Xayah", role: [0, 4], title: "THE REBEL" },
    { label: "XIN_ZHAO", name: "Xin Zhao", role: [0, 2], title: "THE SENESCHAL OF DEMACIA" },
    { label: "YASUO", name: "Yasuo", role: [0, 1, 3, 4], title: "THE UNFORGIVEN" },
    { label: "YONE", name: "Yone", role: [0, 1, 2, 3], title: "THE UNFORGOTTEN" },
    { label: "YUUMI", name: "Yuumi", role: [0, 5], title: "THE MAGICAL CAT" },
    { label: "ZED", name: "Zed", role: [0, 1, 2, 3], title: "THE MASTER OF SHADOWS" },
    { label: "ZERI", name: "Zeri", role: [0, 4], title: "THE SPARK OF ZAUN" },
    { label: "ZIGGS", name: "Ziggs", role: [0, 3, 4], title: "THE HEXPLOSIVES EXPERT" },
    { label: "ZOE", name: "Zoe", role: [0, 3], title: "THE ASPECT OF TWILIGHT" },
    { label: "ZYRA", name: "Zyra", role: [0, 3, 5], title: "RISE OF THE THORNS" }
]
