export const navItems = [
    { label: "Home", to: "/" },
    { label: "Tier List", to: "/tierlist" }
];

export const allChampions = [
    { label: "AATROX", name: "Aatrox"},
    { label: "AHRI", name: "Ahri"},
    { label: "AKALI", name: "Akali"},
    { label: "AKSHAN", name: "Akshan"},
    { label: "ALISTAR", name: "Alistar"},
    { label: "AMUMU", name: "Amumu"},
    { label: "ANNIE", name: "Annie"},
    { label: "ASHE", name: "Ashe"},
    { label: "AURELION_SOL", name: "Aurelion Sol"},
    { label: "BLITZCRANK", name: "Blitzcrank"},
    { label: "BRAND", name: "Brand"},
    { label: "BRAUM", name: "Braum"},
    { label: "CAITLYN", name: "Caitlyn"},
    { label: "CAMILLE", name: "Camille"},
    { label: "CORKI", name: "Corki"},
    { label: "DARIUS", name: "Darius"},
    { label: "DIANA", name: "Diana"},
    { label: "DRAVEN", name: "Draven"},
    { label: "EKKO", name: "Ekko"},
    { label: "EVELYNN", name: "Evelynn"},
    { label: "EZREAL", name: "Ezreal"},
    { label: "TWISTED_FATE", name: "Twisted Fate"},
    { label: "FIDDLESTICKS", name: "Fiddlesticks"},
    { label: "FIORA", name: "Fiora"},
    { label: "FIZZ", name: "Fizz"},
    { label: "MISS_FORTUNE", name: "Miss Fortune"},
    { label: "GALIO", name: "Galio"},
    { label: "GAREN", name: "Garen"},
    { label: "GRAGAS", name: "Gragas"},
    { label: "GRAVES", name: "Graves"},
    { label: "GWEN", name: "Gwen"},
    { label: "HECARIM", name: "Hecarim"},
    { label: "IRELIA", name: "Irelia"},
    { label: "JANNA", name: "Janna"},
    { label: "JARVAN_IV", name: "Jarvan IV"},
    { label: "JAX", name: "Jax"},
    { label: "JAYCE", name: "Jayce"},
    { label: "JHIN", name: "Jhin"},
    { label: "JINX", name: "Jinx"},
    { label: "KAISA", name: "Kai\'sa"},
    { label: "KALISTA", name: "Kalista"},
    { label: "KARMA", name: "Karma"},
    { label: "KASSADIN", name: "Kassadin"},
    { label: "KATARINA", name: "Katarina"},
    { label: "KAYLE", name: "Kayle"},
    { label: "KAYN", name: "Kayn"},
    { label: "KENNEN", name: "Kennen"},
    { label: "KHAZIX", name: "Kha\'zix"},
    { label: "KINDRED", name: "Kindred"},
    { label: "LEE_SIN", name: "Lee Sin"},
    { label: "LEONA", name: "Leona"},
    { label: "LILLIA", name: "Lillia"},
    { label: "LUCIAN", name: "Lucian"},
    { label: "LULU", name: "Lulu"},
    { label: "LUX", name: "Lux"},
    { label: "MALPHITE", name: "Malphite"},
    { label: "MORGANA", name: "Morgana"},
    { label: "MASTER_YI", name: "Master Yi"},
    { label: "DR_MUNDO", name: "Dr. Mundo"},
    { label: "NAMI", name: "Nami"},
    { label: "NASUS", name: "Nasus"},
    { label: "NAUTILUS", name: "Nautilus"},
    { label: "NILAH", name: "Nilah"},
    { label: "NUNU_WILLUMP", name: "Nunu & Willump"},
    { label: "OLAF", name: "Olaf"},
    { label: "ORIANNA", name: "Orianna"},
    { label: "ORNN", name: "Ornn"},
    { label: "PANTHEON", name: "Pantheon"},
    { label: "PYKE", name: "Pyke"},
    { label: "RAKAN", name: "Rakan"},
    { label: "RAMMUS", name: "Rammus"},
    { label: "RENEKTON", name: "Renekton"},
    { label: "RENGAR", name: "Rengar"},
    { label: "RIVEN", name: "Riven"},
    { label: "SAMIRA", name: "Samira"},
    { label: "SENNA", name: "Senna"},
    { label: "SERAPHINE", name: "Seraphine"},
    { label: "SETT", name: "Sett"},
    { label: "SHEN", name: "Shen"},
    { label: "SHYVANA", name: "Shyvana"},
    { label: "SINGED", name: "Singed"},
    { label: "SION", name: "Sion"},
    { label: "SIVIR", name: "Sivir"},
    { label: "SONA", name: "Sona"},
    { label: "SORAKA", name: "Soraka"},
    { label: "SWAIN", name: "Swain"},
    { label: "SYNDRA", name: "Syndra"},
    { label: "TALON", name: "Talon"},
    { label: "TEEMO", name: "Teemo"},
    { label: "THRESH", name: "Thresh"},
    { label: "TRISTANA", name: "Tristana"},
    { label: "TRYNDAMERE", name: "Tryndamere"},
    { label: "TWITCH", name: "Twitch"},
    { label: "URGOT", name: "Urgot"},
    { label: "VARUS", name: "Varus"},
    { label: "VAYNE", name: "Vayne"},
    { label: "VEIGAR", name: "Veigar"},
    { label: "VEIGO", name: "Veigo"},
    { label: "VEX", name: "Vex"},
    { label: "VI", name: "Vi"},
    { label: "VLADIMIR", name: "Vladimir"},
    { label: "VOLIBEAR", name: "Volibear"},
    { label: "WARWICK", name: "Warwick"},
    { label: "WUKONG", name: "Wukong"},
    { label: "XAYAH", name: "Xayah"},
    { label: "XIN_ZHAO", name: "Xin Zhao"},
    { label: "YASUO", name: "Yasuo"},
    { label: "YONE", name: "Yone"},
    { label: "YUUMI", name: "Yuumi"},
    { label: "ZED", name: "Zed"},
    { label: "ZERI", name: "Zeri"},
    { label: "ZIGGS", name: "Ziggs"},
    { label: "ZOE", name: "Zoe"},
    { label: "ZYRA", name: "Zyra"},
]