export const navItems = [
    { label: "Home", to: "/" },
    { label: "Tier List", to: "/tierlist" }
];

export const regionRankPatch = [
    { label: "\"Global\"", imgSrc: "assets/misc/global-icon.svg"},
    { label: "Diamond+", imgSrc: "assets/misc/diamond-icon.png"},
    { label: "Version: 5.1B", imgSrc: "/"}
];

export const allChampions = [
    { label: "AATROX", name: "Aatrox", role: [0, 1, ]},
    { label: "AHRI", name: "Ahri", role: [0, 3, ]},
    { label: "AKALI", name: "Akali", role: [0, 1, 3, 5, ]},
    { label: "AKSHAN", name: "Akshan", role: [0, 1, 3, ]},
    { label: "ALISTAR", name: "Alistar", role: [0, ]},
    { label: "AMUMU", name: "Amumu", role: [0, 2, ]},
    { label: "ANNIE", name: "Annie", role: [0, 3, ]},
    { label: "ASHE", name: "Ashe", role: [0, 4, 5, ]},
    { label: "AURELION_SOL", name: "Aurelion Sol", role: [0, 3, ]},
    { label: "BLITZCRANK", name: "Blitzcrank", role: [0, 5, ]},
    { label: "BRAND", name: "Brand", role: [0, 3, 5, ]},
    { label: "BRAUM", name: "Braum", role: [0, 5, ]},
    { label: "CAITLYN", name: "Caitlyn", role: [0, 4, ]},
    { label: "CAMILLE", name: "Camille", role: [0, 1, ]},
    { label: "CORKI", name: "Corki", role: [0, 3, 4, ]},
    { label: "DARIUS", name: "Darius", role: [0, 1, ]},
    { label: "DIANA", name: "Diana", role: [0, 2, 3, ]},
    { label: "DRAVEN", name: "Draven", role: [0, 4, ]},
    { label: "EKKO", name: "Ekko", role: [0, 2, 3, ]},
    { label: "EVELYNN", name: "Evelynn", role: [0, 2, ]},
    { label: "EZREAL", name: "Ezreal", role: [0, 4, ]},
    { label: "FIDDLESTICKS", name: "Fiddlesticks", role: [0, 2, ]},
    { label: "FIORA", name: "Fiora", role: [0, 1, ]},
    { label: "FIZZ", name: "Fizz", role: [0, 3, ]},
    { label: "GALIO", name: "Galio", role: [0, 3, ]},
    { label: "GAREN", name: "Garen", role: [0, 1, ]},
    { label: "GRAGAS", name: "Gragas", role: [0, 1, 2, 3, ]},
    { label: "GRAVES", name: "Graves", role: [0, 2, ]},
    { label: "GWEN", name: "Gwen", role: [0, 1, 2, ]},
    { label: "HECARIM", name: "Hecarim", role: [0, 2, ]},
    { label: "IRELIA", name: "Irelia", role: [0, 1, 3, ]},
    { label: "JANNA", name: "Janna", role: [0, 5, ]},
    { label: "JARVAN_IV", name: "Jarvan IV", role: [0, 2, ]},
    { label: "JAX", name: "Jax", role: [0, 1, 2, ]},
    { label: "JAYCE", name: "Jayce", role: [0, 1, 3, ]},
    { label: "JHIN", name: "Jhin", role: [0, 4, ]},
    { label: "JINX", name: "Jinx", role: [0, 4, ]},
    { label: "KAISA", name: "Kai\'sa", role: [0, 4, ]},
    { label: "KALISTA", name: "Kalista", role: [0, 4, ]},
    { label: "KARMA", name: "Karma", role: [0, 3, 5, ]},
    { label: "KASSADIN", name: "Kassadin", role: [0, 3, ]},
    { label: "KATARINA", name: "Katarina", role: [0, 3, ]},
    { label: "KAYLE", name: "Kayle", role: [0, 1, 3, ]},
    { label: "KAYN", name: "Kayn", role: [0, 2, ]},
    { label: "KENNEN", name: "Kennen", role: [0, 1, 3, ]},
    { label: "KHAZIX", name: "Kha\'zix", role: [0, 2, ]},
    { label: "KINDRED", name: "Kindred", role: [0, 2, ]},
    { label: "LEE_SIN", name: "Lee Sin", role: [0, 2, ]},
    { label: "LEONA", name: "Leona", role: [0, 5, ]},
    { label: "LILLIA", name: "Lillia", role: [0, 2, ]},
    { label: "LUCIAN", name: "Lucian", role: [0, 4, ]},
    { label: "LULU", name: "Lulu", role: [0, 5, ]},
    { label: "LUX", name: "Lux", role: [0, 3, 5, ]},
    { label: "MALPHITE", name: "Malphite", role: [0, 1, 3, ]},
    { label: "MASTER_YI", name: "Master Yi", role: [0, 2, ]},
    { label: "MISS_FORTUNE", name: "Miss Fortune", role: [0, 4, ]},
    { label: "MORGANA", name: "Morgana", role: [0, 2, 5, ]},
    { label: "DR_MUNDO", name: "Dr. Mundo", role: [0, 1, ]},
    { label: "NAMI", name: "Nami", role: [0, 5, ]},
    { label: "NASUS", name: "Nasus", role: [0, 1, ]},
    { label: "NAUTILUS", name: "Nautilus", role: [0, 5, ]},
    { label: "NILAH", name: "Nilah", role: [0, 4, ]},
    { label: "NUNU_WILLUMP", name: "Nunu & Willump", role: [0, 2, ]},
    { label: "OLAF", name: "Olaf", role: [0, 1, ]},
    { label: "ORIANNA", name: "Orianna", role: [0, 3, ]},
    { label: "ORNN", name: "Ornn", role: [0, 1, ]},
    { label: "PANTHEON", name: "Pantheon", role: [0, 1, 2, 3, 5, ]},
    { label: "PYKE", name: "Pyke", role: [0, 5, ]},
    { label: "RAKAN", name: "Rakan", role: [0, 5, ]},
    { label: "RAMMUS", name: "Rammus", role: [0, 2, ]},
    { label: "RENEKTON", name: "Renekton", role: [0, 1, ]},
    { label: "RENGAR", name: "Rengar", role: [0, 1, 2, ]},
    { label: "RIVEN", name: "Riven", role: [0, 1, ]},
    { label: "SAMIRA", name: "Samira", role: [0, 4, ]},
    { label: "SENNA", name: "Senna", role: [0, 5, ]},
    { label: "SERAPHINE", name: "Seraphine", role: [0, 3, 4, 5, ]},
    { label: "SETT", name: "Sett", role: [0, 1, ]},
    { label: "SHEN", name: "Shen", role: [0, 1, ]},
    { label: "SHYVANA", name: "Shyvana", role: [0, 2, ]},
    { label: "SINGED", name: "Singed", role: [0, 1, ]},
    { label: "SION", name: "Sion", role: [0, 1, ]},
    { label: "SIVIR", name: "Sivir", role: [0, 4, ]},
    { label: "SONA", name: "Sona", role: [0, 5, ]},
    { label: "SORAKA", name: "Soraka", role: [0, 5, ]},
    { label: "SWAIN", name: "Swain", role: [0, 3, 5, ]},
    { label: "SYNDRA", name: "Syndra", role: [0, 3, ]},
    { label: "TALON", name: "Talon", role: [0, 2, 3, ]},
    { label: "TEEMO", name: "Teemo", role: [0, 1, ]},
    { label: "THRESH", name: "Thresh", role: [0, 5, ]},
    { label: "TRISTANA", name: "Tristana", role: [0, 3, 4, ]},
    { label: "TRYNDAMERE", name: "Tryndamere", role: [0, 1, ]},
    { label: "TWISTED_FATE", name: "Twisted Fate", role: [0, 1, 3, ]},
    { label: "TWITCH", name: "Twitch", role: [0, 4, ]},
    { label: "URGOT", name: "Urgot", role: [0, 1, ]},
    { label: "VARUS", name: "Varus", role: [0, 1, 4, ]},
    { label: "VAYNE", name: "Vayne", role: [0, 1, 4, ]},
    { label: "VEIGAR", name: "Veigar", role: [0, 3, ]},
    { label: "VEIGO", name: "Veigo", role: [0, 2, ]},
    { label: "VEX", name: "Vex", role: [0, 3, ]},
    { label: "VI", name: "Vi", role: [0, 2, ]},
    { label: "VLADIMIR", name: "Vladimir", role: [0, 1, 3, ]},
    { label: "VOLIBEAR", name: "Volibear", role: [0, 1, 2, ]},
    { label: "WARWICK", name: "Warwick", role: [0, 1, 2, ]},
    { label: "WUKONG", name: "Wukong", role: [0, 1, 2, ]},
    { label: "XAYAH", name: "Xayah", role: [0, 4, ]},
    { label: "XIN_ZHAO", name: "Xin Zhao", role: [0, 2, ]},
    { label: "YASUO", name: "Yasuo", role: [0, 1, 3, 4, ]},
    { label: "YONE", name: "Yone", role: [0, 1, 3, ]},
    { label: "YUUMI", name: "Yuumi", role: [0, 5, ]},
    { label: "ZED", name: "Zed", role: [0, 1, 2, 3, ]},
    { label: "ZERI", name: "Zeri", role: [0, 4, ]},
    { label: "ZIGGS", name: "Ziggs", role: [0, 3, 4, ]},
    { label: "ZOE", name: "Zoe", role: [0, 3, ]},
    { label: "ZYRA", name: "Zyra", role: [0, 3, 5, ]}
]